// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Obligaciones.Models;

namespace Obligaciones.Migrations
{
    [DbContext(typeof(ObligacionesContext))]
    [Migration("20191011212655_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Obligaciones.Models.Address", b =>
                {
                    b.Property<long>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ContributorId");

                    b.Property<string>("Ext");

                    b.Property<string>("Int");

                    b.Property<string>("State");

                    b.Property<string>("Street");

                    b.Property<string>("Suburb");

                    b.Property<string>("Town");

                    b.Property<string>("Zip");

                    b.HasKey("AddressId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Obligaciones.Models.Contributor", b =>
                {
                    b.Property<long>("ContributorId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("RFC");

                    b.Property<long?>("WorkLoadRegistryId");

                    b.HasKey("ContributorId");

                    b.HasIndex("WorkLoadRegistryId");

                    b.ToTable("Contributors");
                });

            modelBuilder.Entity("Obligaciones.Models.Debt", b =>
                {
                    b.Property<long>("DebtId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ContributorId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<long>("ObligationId");

                    b.Property<int>("Origin");

                    b.Property<int>("Status");

                    b.Property<int>("TaxType");

                    b.Property<double>("Total");

                    b.Property<int>("Type");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<DateTime>("Validity");

                    b.HasKey("DebtId");

                    b.ToTable("Debts");
                });

            modelBuilder.Entity("Obligaciones.Models.Estate", b =>
                {
                    b.Property<long>("EstateId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Area");

                    b.Property<double>("Construction");

                    b.Property<long>("ContributorId");

                    b.Property<string>("Key");

                    b.Property<double>("Price");

                    b.Property<int>("Type");

                    b.HasKey("EstateId");

                    b.ToTable("Estates");
                });

            modelBuilder.Entity("Obligaciones.Models.Obligation", b =>
                {
                    b.Property<long>("ObligationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AllowUpdates");

                    b.Property<bool>("ApplyTaxes");

                    b.Property<string>("Description");

                    b.Property<string>("Fundament");

                    b.Property<string>("Key");

                    b.Property<int>("PersonType");

                    b.Property<int>("Type");

                    b.Property<DateTime>("Valitity");

                    b.HasKey("ObligationId");

                    b.ToTable("Obligations");
                });

            modelBuilder.Entity("Obligaciones.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Obligaciones.Models.WorkLoad", b =>
                {
                    b.Property<long>("WorkLoadId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<long>("UserId");

                    b.HasKey("WorkLoadId");

                    b.HasIndex("UserId");

                    b.ToTable("WorkLoads");
                });

            modelBuilder.Entity("Obligaciones.Models.WorkLoadRegistry", b =>
                {
                    b.Property<long>("WorkLoadRegistryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Name");

                    b.Property<string>("RFC");

                    b.Property<int>("Type");

                    b.Property<long>("WorkLoadId");

                    b.HasKey("WorkLoadRegistryId");

                    b.HasIndex("WorkLoadId");

                    b.ToTable("WorkLoadRegistries");
                });

            modelBuilder.Entity("Obligaciones.Models.Contributor", b =>
                {
                    b.HasOne("Obligaciones.Models.WorkLoadRegistry")
                        .WithMany("Contributors")
                        .HasForeignKey("WorkLoadRegistryId");
                });

            modelBuilder.Entity("Obligaciones.Models.WorkLoad", b =>
                {
                    b.HasOne("Obligaciones.Models.User")
                        .WithMany("WorkLoads")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Obligaciones.Models.WorkLoadRegistry", b =>
                {
                    b.HasOne("Obligaciones.Models.WorkLoad")
                        .WithMany("WorkLoadRegistries")
                        .HasForeignKey("WorkLoadId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
